--------------------------------------------------------
--  파일이 생성됨 - 일요일-5월-21-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table AUTHORITY
--------------------------------------------------------

  CREATE TABLE "BOARD"."AUTHORITY" 
   (	"USERNAME" VARCHAR2(20 BYTE), 
	"AUTHORITY_NAME" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BOARD" ;
--------------------------------------------------------
--  DDL for Table BOARD_PRO
--------------------------------------------------------

  CREATE TABLE "BOARD"."BOARD_PRO" 
   (	"BNO" NUMBER(*,0), 
	"SUBJECT" VARCHAR2(50 BYTE), 
	"CONTENT" VARCHAR2(1024 BYTE), 
	"WRITER" VARCHAR2(50 BYTE), 
	"REG_DATE" DATE, 
	"HIT" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BOARD" ;

   COMMENT ON COLUMN "BOARD"."BOARD_PRO"."BNO" IS '기본키';
   COMMENT ON COLUMN "BOARD"."BOARD_PRO"."SUBJECT" IS '타이틀';
   COMMENT ON COLUMN "BOARD"."BOARD_PRO"."CONTENT" IS '내용';
   COMMENT ON COLUMN "BOARD"."BOARD_PRO"."WRITER" IS '작성자';
   COMMENT ON COLUMN "BOARD"."BOARD_PRO"."REG_DATE" IS '게시일';
   COMMENT ON COLUMN "BOARD"."BOARD_PRO"."HIT" IS '읽은수';
--------------------------------------------------------
--  DDL for Table BOARDCONFIG
--------------------------------------------------------

  CREATE TABLE "BOARD"."BOARDCONFIG" 
   (	"BOARD_TABLE" VARCHAR2(50 BYTE), 
	"BOARD_TITLE" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BOARD" ;

   COMMENT ON COLUMN "BOARD"."BOARDCONFIG"."BOARD_TABLE" IS '테이블명';
   COMMENT ON COLUMN "BOARD"."BOARDCONFIG"."BOARD_TITLE" IS '게시판이름';
--------------------------------------------------------
--  DDL for Table MEMBER
--------------------------------------------------------

  CREATE TABLE "BOARD"."MEMBER" 
   (	"USERNAME" VARCHAR2(20 BYTE), 
	"PASSWORD" VARCHAR2(500 BYTE), 
	"NAME" VARCHAR2(20 BYTE), 
	"IS_ACCOUNT_NON_EXPIRED" VARCHAR2(1 BYTE), 
	"IS_ACCOUNT_NON_LOCKED" VARCHAR2(1 BYTE), 
	"IS_CREDENTIALS_NON_EXPIRED" VARCHAR2(1 BYTE), 
	"IS_ENABLED" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BOARD" ;
REM INSERTING into BOARD.AUTHORITY
SET DEFINE OFF;
REM INSERTING into BOARD.BOARD_PRO
SET DEFINE OFF;
Insert into BOARD.BOARD_PRO (BNO,SUBJECT,CONTENT,WRITER,REG_DATE,HIT) values (9,'ㅂ',null,'ㅁㄴㅇ',to_date('17/05/19','RR/MM/DD'),4);
Insert into BOARD.BOARD_PRO (BNO,SUBJECT,CONTENT,WRITER,REG_DATE,HIT) values (21,'ㅁㄴㅇ','난좀 천재인듯?','ㅁㄴㅇ',to_date('17/05/21','RR/MM/DD'),9);
Insert into BOARD.BOARD_PRO (BNO,SUBJECT,CONTENT,WRITER,REG_DATE,HIT) values (1,'ㅁㄴㅇ','개쌔까!!!!','ㅁㄴㅇ',to_date('17/05/19','RR/MM/DD'),12);
Insert into BOARD.BOARD_PRO (BNO,SUBJECT,CONTENT,WRITER,REG_DATE,HIT) values (4,'ㅁㄴㅇ','dasdasd','ㅁㄴㅇ',to_date('17/05/19','RR/MM/DD'),0);
Insert into BOARD.BOARD_PRO (BNO,SUBJECT,CONTENT,WRITER,REG_DATE,HIT) values (7,'ㅋㅋㅋㅋㅋ','난 역시 천재야','ㅁㄴㅇ',to_date('17/05/19','RR/MM/DD'),2);
REM INSERTING into BOARD.BOARDCONFIG
SET DEFINE OFF;
Insert into BOARD.BOARDCONFIG (BOARD_TABLE,BOARD_TITLE) values ('pro','테스트');
REM INSERTING into BOARD.MEMBER
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index BOARD_PRO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOARD"."BOARD_PRO_PK" ON "BOARD"."BOARD_PRO" ("BNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BOARD" ;
--------------------------------------------------------
--  DDL for Index BOARD_CONFIG_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOARD"."BOARD_CONFIG_PK" ON "BOARD"."BOARDCONFIG" ("BOARD_TABLE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BOARD" ;
--------------------------------------------------------
--  DDL for Index MEMBER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOARD"."MEMBER_PK" ON "BOARD"."MEMBER" ("USERNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BOARD" ;
--------------------------------------------------------
--  Constraints for Table AUTHORITY
--------------------------------------------------------

  ALTER TABLE "BOARD"."AUTHORITY" MODIFY ("AUTHORITY_NAME" NOT NULL ENABLE);
  ALTER TABLE "BOARD"."AUTHORITY" MODIFY ("USERNAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BOARD_PRO
--------------------------------------------------------

  ALTER TABLE "BOARD"."BOARD_PRO" ADD CONSTRAINT "BOARD_PRO_PK" PRIMARY KEY ("BNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BOARD"  ENABLE;
  ALTER TABLE "BOARD"."BOARD_PRO" MODIFY ("REG_DATE" NOT NULL ENABLE);
  ALTER TABLE "BOARD"."BOARD_PRO" MODIFY ("WRITER" NOT NULL ENABLE);
  ALTER TABLE "BOARD"."BOARD_PRO" MODIFY ("SUBJECT" NOT NULL ENABLE);
  ALTER TABLE "BOARD"."BOARD_PRO" MODIFY ("BNO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BOARDCONFIG
--------------------------------------------------------

  ALTER TABLE "BOARD"."BOARDCONFIG" ADD CONSTRAINT "BOARD_CONFIG_PK" PRIMARY KEY ("BOARD_TABLE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BOARD"  ENABLE;
  ALTER TABLE "BOARD"."BOARDCONFIG" MODIFY ("BOARD_TABLE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MEMBER
--------------------------------------------------------

  ALTER TABLE "BOARD"."MEMBER" ADD CONSTRAINT "MEMBER_PK" PRIMARY KEY ("USERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BOARD"  ENABLE;
  ALTER TABLE "BOARD"."MEMBER" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "BOARD"."MEMBER" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "BOARD"."MEMBER" MODIFY ("USERNAME" NOT NULL ENABLE);
